name: 'Licence checker'
description: 'Checks for open source licence.'
inputs:
  LC_URL:
    required: true
runs:
  using: "composite"
  steps: 
    - run: |
        mkdir -p /lc
        curl -o /lc/licence-checker -L $LC_URL
        chmod +x /lc/licence-checker
        find . -regex "\(COPYING\|LICENSE\|.*\.\(py\|java\|kt\|cs\|proto\|js\|ts\)\)$" | xargs -n1 /lc/licence-checker
      shell: bash
      env:
        LC_URL: ${{ inputs.LC_URL }}
