name: 'Licence checker'
description: 'Checks for open source licence.'
inputs:
  LC_URL:
    description: "URL used to download licence-checker binary"
    required: false
    default: "https://github.com/zepben/licence-checker/releases/latest/download/licence-checker"
  PATH:
    description: "Path to search for files to check."
    required: false
    default: "."
runs:
  using: "composite"
  steps: 
    - run: |
        mkdir -p /lc
        if ! [ -f /lc/licence-checker ]; then
          curl -o /lc/licence-checker -L $LC_URL
        fi
        chmod +x /lc/licence-checker
        if [ "$(gh repo view --json isPrivate | jq .isPrivate)" == "true" ]; then
          echo "Repo is private"
          licence_type="private"
        else
          echo "Repo is public"
          licence_type="public"
        fi
        echo "Will test ${licence_type} licence"
        find $SEARCHPATH -regex "\(COPYING\|LICENSE\|.*\.\(py\|java\|kt\|cs\|proto\|js\|ts\)\)$" | xargs -I {} /lc/licence-checker {} "${licence_type}"
      shell: bash
      env:
        LC_URL: ${{ inputs.LC_URL }}
        SEARCHPATH: ${{ inputs.PATH  }}
