name: 'Licence checker'
description: 'Checks for open source licence.'
inputs:
  LC_URL:
    required: true
runs:
  using: "composite"
  steps: 
    - name: create lc directory
      run: mkdir ~/lc
      shell: bash

    - name: Cache licence-check
      uses: actions/cache@v2
      with:
        path: ~/lc
        key: lc
        
    - run: |
        curl -o ~/lc/licence-checker -L $LC_URL
        chmod +x ~/lc/licence-checker
        find -regextype posix-egrep -regex "(COPYING|.*\.(py|java|kt|cs|proto|js|ts))$" | xargs -n1 ~/lc/licence-checker
      shell: bash
      env:
        LC_URL: ${{ inputs.LC_URL }}